name: CI/CD Pipeline - Docker Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cap nhat code va restart Docker
        run: |
          git pull origin main
          docker compose down
          docker compose up -d --build
          docker image prune -f 